### ISSUE TITLE
SIKEp434 --parallel Errors

### ISSUE THREAD

**Issue by 0xmachos** [jack4818/Castryck-Decru-SageMath#16] opened 2022-08-09 15:43 UTC
macOS: `13.0` Public Beta (`22A5311f`)
Hardware: M1 Max 32GB
SageMath: `9.6` (From [3-manifolds/Sage_macOS](https://github.com/3-manifolds/Sage_macOS/releases/tag/v1.4.2))
Repo Version: commit `1e6341296f85004caf80ac2a43cb011c2fd2cfa2`

When I run
```
sage SIKEp434.sage --parallel 
```
The attack completes within seconds but there's lots of python errors (See screenshot and attached text file with full terminal output). There's no way the attack can run this fast I assume?

<img width="1025" alt="sage SIKEp434 sage --parallel error" src="https://user-images.githubusercontent.com/30755149/183696965-1a29ea64-92aa-4197-93e1-51206395474a.png">

[sage SIKEp434.sage --parallel.txt](https://github.com/jack4818/Castryck-Decru-SageMath/files/9292535/sage.SIKEp434.sage.--parallel.txt)

**Comment by GiacomoPope** [comment] 2022-08-09 16:36
Hmmm parallel compute stuff is dark waters. We've had other people get it to work but no one using the SageMath binary you have. 

The key is printed out above though and the script isn't saying "something went wrong" so this is a weird bug indeed.

Could you check whether the recovered ternary digits match the prediction outputted at the beginning?

**Comment by 0xmachos** [comment] 2022-08-09 16:44
> Could you check whether the recovered ternary digits match the prediction outputted at the beginning?

They do not match.

```
If all goes well then the following digits should be found: 
[1, 0, 0, 0, 2, 2, 1, 2, 0, 0, 2, 1, 1, 2, 0, 1, 2, 0, 1, 2, 1, 0, 2, 0, 1, 1, 1, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2, 0, 1, 1, 0, 0, 1, 2, 1, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 2, 1, 0, 2, 1, 2, 2, 1, 2, 0, 2, 0, 0, 1, 0, 0, 2, 0, 2, 0, 2, 1, 0, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 0, 2, 1, 1, 1, 0, 2, 1, 1, 0, 1, 0, 2, 2, 2, 0, 2, 0, 0, 1, 0, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 0, 2, 0, 0, 0, 0, 1, 0, 1, 2, 0, 1]
```

```
Bob's secret key revealed as: 46194451761550288692688972058651882971893359443354718101688692185
In ternary, this is: 

[0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 2, 1]
```

**Comment by GiacomoPope** [comment] 2022-08-09 22:30
haha ok, so it's totally broken then. With all those python errors I doubt I can bug fix without more context. Maybe just paste all the output here and I can attempt to guess what the problem is

**Comment by 0xmachos** [comment] 2022-08-09 23:06
Full terminal output linked in the OP, [sage SIKEp434.sage --parallel.txt](https://github.com/jack4818/Castryck-Decru-SageMath/files/9292535/sage.SIKEp434.sage.--parallel.txt)

I updated the OP to add my hardware, M1 Max 32GB.

Don't feel obligated to work on this, I just thought yous would want to know. I'm not expecting a fix etc.

If you need any other info from me or want me to run test code etc let me know. Happy to help.

**Comment by 0xmachos** [comment] 2022-08-09 23:14
Same thing on b92c72639d2882892ea44284740e0e09edc01da8.

```
$ sage SIKEp434.sage --parallel
Running the attack against SIKEp434 parameters, which has a prime: 2^216*3^137 - 1
Generating public data for the attack...
If all goes well then the following digits should be found: 
[2, 0, 1, 2, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 2, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 2, 1, 2, 2, 0, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 1, 1, 1, 0, 0, 1, 2, 2, 0, 1, 0, 0, 1, 1, 2, 0, 1, 2, 1, 2, 0, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 0, 1, 0, 2, 2, 0, 1, 1, 2, 1, 2, 1, 0, 0, 2, 0, 1, 1, 2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 0, 0, 2, 0, 2, 0, 2, 1, 1, 0, 2, 2, 2, 0, 1]
Performing the attack in parallel using 10 cores
```

```
Bob's secret key revealed as: 72055221764326555681266580048438165045149953392498563601170185131
In ternary, this is: 
[1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 2, 2]
```

[sage SIKEp434.sage --parallel.txt - b92c726.txt](https://github.com/jack4818/Castryck-Decru-SageMath/files/9295101/sage.SIKEp434.sage.--parallel.txt.-.b92c726.txt)

**Comment by 0xmachos** [comment] 2022-08-09 23:21
If I set `num_cores = 1` and then run `sage SIKEp434.sage --parallel` it still solves quickly but incorrectly. 

```
$ sage SIKEp434.sage --parallel                                                                                                                                (main)
Running the attack against SIKEp434 parameters, which has a prime: 2^216*3^137 - 1
Generating public data for the attack...
If all goes well then the following digits should be found: [2, 0, 0, 2, 0, 1, 1, 0, 2, 2, 2, 1, 1, 1, 1, 1, 0, 2, 0, 0, 1, 2, 2, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 0, 0, 2, 0, 2, 1, 0, 2, 1, 2, 2, 0, 0, 0, 2, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 2, 2, 1, 1, 2, 2, 0, 1, 0, 2, 1, 2, 0, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 2, 0, 2, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 2, 2, 2, 0, 2, 0, 0, 2, 1, 2, 2, 1, 2, 1, 2, 0, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2]
Performing the attack in parallel using 1 cores
```

```
Bob's secret key revealed as: 8595044557171427132038716315969726107279416250769088168531684569
In ternary, this is: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
Altogether this took 2.565402030944824 seconds.
```

**Comment by yyyyx4** [comment] 2022-08-10 01:21
Interesting. For debugging, could you please add the lines
```python
for f in two_i:
    print('<<<<')
    print(f)
    print(f.kernel_polynomial())
    print(f.get_pre_isomorphism())
    print(f.get_post_isomorphism())
    print(f.rational_maps())
    print('>>>>')
```
after
```
# ===================================
# =====  ATTACK  ====================
# ===================================
```
in `SIKEp434.sage` and show us the full output (including the error messages) again?

Does the error disappear if you replace `generate_automorphism` in `public_values_aux.sage` by the following?
```python
def generate_automorphism(E):
    if E.a_invariants() != (0,6,0,1,0):
        raise NotImplementedError
    return E.isogeny(E.lift_x(1), codomain=E)
```

**Comment by 0xmachos** [comment] 2022-08-12 13:53
Happy to help keep testing but does this matter now we have 91d7e43c0626dec1dabf6dd1367541070e3f233f?

**Comment by GiacomoPope** [comment] 2022-08-12 13:54
Your bug should still remain I think?

**Comment by 0xmachos** [comment] 2022-08-12 18:24
I now get the following.
```
$ sage SIKEp434.sage --parallel
Running the attack against SIKEp434 parameters, which has a prime: 2^216*3^137 - 1
Generating public data for the attack...
If all goes well then the following digits should be found: [1, 1, 2, 2, 0, 1, 1, 1, 2, 0, 2, 2, 0, 0, 0, 2, 1, 0, 2, 1, 0, 2, 0, 0, 2, 2, 2, 1, 2, 0, 2, 1, 0, 2, 0, 0, 0, 1, 1, 2, 0, 1, 2, 2, 0, 1, 2, 1, 1, 0, 1, 0, 1, 2, 0, 2, 0, 2, 0, 2, 1, 0, 1, 0, 1, 2, 2, 0, 2, 0, 0, 2, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 1, 0, 1, 2, 0, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 1, 1, 0, 1, 1, 0, 2, 1, 0, 2, 2, 2, 0, 2, 2, 1, 0, 1, 2, 0, 2, 1, 0, 2]
Performing the attack in parallel using 10 cores
Determination of first 2 ternary digits. We are working with 2^216-torsion.
------------------------------------------------------------------------
Glue-and-split! These are most likely the secret digits.
Traceback (most recent call last):
  File "/Users/mikey/Documents/Projects/Castryck-Decru-SageMath/SIKEp434.sage.py", line 62, in <module>
    recovered_key = RunAttack(num_cores)
  File "/Users/mikey/Documents/Projects/Castryck-Decru-SageMath/SIKEp434.sage.py", line 53, in RunAttack
    return CastryckDecruAttack(E_start, P2, Q2, EB, PB, QB, two_i, num_cores=num_cores)
  File "<string>", line 206, in CastryckDecruAttack
TypeError: can't multiply sequence by non-int of type 'EllipticCurvePoint_finite_field'
```

I'm on commit bf9fe8a86de7295524f134095d62f26f498f0049.

**Comment by GiacomoPope** [comment] 2022-08-18 13:15
I'm so confused by your errors... My only thought is it is how you are installing Sage, and that doing something like `brew install sage` will get you something which links up more nicely on your machine.

**Comment by Quasar0147** [comment] 2022-08-22 14:38
sage SIKEp434.sage --parallel works for me on Mac M1 (12.2) and sage 9.6 (commit: a4928b0cf450b765c3bde6e5328f0146603526a8). Its most likely with your sage. Ill try redownloading sage to the newest version to check though!

**Comment by GiacomoPope** [comment] 2022-09-10 20:31
I think im going to close this, feel like something odd is happening with the 3-manifolds install, which we cant fix our side.

**Closed as completed by GiacomoPope** 2022-09-10 20:31 UTC
